const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/safestance");

const bizProfile = [
  {
    bizname: "Safeway",
    email: "joesmith@safeway.com",
    address: "1601 Coalton Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipNHF0IUOK3yFeKKdHE_JxtRya1nWgP9ICIKWH2R=w426-h240-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
  opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Walmart Supercenter",
    email: "joesmith@safeway.com",
    address: " 500 Summit Blvd, Broomfield, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipPTnahHOSAEIL1PoYYVWC1HfOke9TovKb7ReMrN=w426-h240-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Walgreens",
    email: "joesmith@safeway.com",
    address: " 1600 Coalton Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipOwjd6JySnFAo-LUSLJGji_MU39CZ-Yptd387dE=w408-h306-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Target",
    email: "joesmith@safeway.com",
    address: " 400 Marshall Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipNdOKcWmGypwbR7d_OVC3gsi0tan_e0WyvGBEYb=w426-h240-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Michaels",
    email: "joesmith@safeway.com",
    address: " 410 Marshall Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipMVbnUv4JEFFl1iW_apVZYVlHy89VS6J2M_ae2K=w408-h306-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Starbucks",
    email: "joesmith@safeway.com",
    address: " 2800 Rock Creek Cir A1, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipPiDx3dBnPpri3nhs_NWCdX9DLLEDZQjv6xcP4D=w408-h306-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Whole Foods Market",
    email: "joesmith@safeway.com",
    address: " 303 Marshall Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipPtpwDjDrdQUuHsvtGCD7xhLc1odMEg25wy1VH-=w408-h408-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "T.J. Maxx",
    email: "joesmith@safeway.com",
    address: " 510 Marshall Rd, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipM_qEtfuhPOkTzbhbjOQwKBnPVqFX3zR913wj08=w426-h240-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "OfficeMax",
    email: "joesmith@safeway.com",
    address: " 410 Center Dr, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipNILhkKvCveHkbHBHPxa5_3NVFZdkDZXOpg7eoq=w408-h272-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "PetSmart",
    email: "joesmith@safeway.com",
    address: " 402 Center Dr, Superior, CO",
    zip: "80027",
    image: "https://lh5.googleusercontent.com/p/AF1QipOmAETweg90_QJlbitDXz94EstGVJi2QDNLYyib=w408-h306-k-no",
    geometry: [],
    types: {},
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    rating: 0,
    opening_hours: [],
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
];

db.Business.remove({})
  .then(() => db.Business.collection.insertMany(bizProfile))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
 