const mongoose = require("mongoose");
const db = require("../models");

// This file empties the Books collection and inserts the books below

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/safestance");

const bizProfile = [
  {
    bizname: "Safeway",
    email: "joesmith@safeway.com",
    address: "1601 Coalton Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Walmart Supercenter",
    email: "joesmith@safeway.com",
    address: " 500 Summit Blvd, Broomfield, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Walgreens",
    email: "joesmith@safeway.com",
    address: " 1600 Coalton Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Target",
    email: "joesmith@safeway.com",
    address: " 400 Marshall Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Michaels",
    email: "joesmith@safeway.com",
    address: " 410 Marshall Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Starbucks",
    email: "joesmith@safeway.com",
    address: " 2800 Rock Creek Cir A1, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "Whole Foods Market",
    email: "joesmith@safeway.com",
    address: " 303 Marshall Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "T.J. Maxx",
    email: "joesmith@safeway.com",
    address: " 510 Marshall Rd, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "OfficeMax",
    email: "joesmith@safeway.com",
    address: " 410 Center Dr, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
  {
    bizname: "PetSmart",
    email: "joesmith@safeway.com",
    address: " 402 Center Dr, Superior, CO",
    zip: "80027",
    maskthumbsup: 0,
    maskthumbsdown: 0,
    santhumbsup: 0,
    santhumbsdown: 0,
    disthumbsup: 0,
    disthumbsdown: 0,
    cashthumbsup: 0,
    cashthumbsdown: 0,
    instore: 0,
    inline: 0,
    storeopen: 9,
    storeclose: 5,
    creationdate: new Date(Date.now()),
  },
];

db.Business.remove({})
  .then(() => db.Business.collection.insertMany(bizProfile))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
